/**
 * Tailwind config for the self-hosted CSS build.
 *
 * The static `shared-frontend/tailwind.css` is generated by scanning every
 * .html and .js file under shared-frontend/ for Tailwind class tokens.
 * Re-generate after class changes:
 *
 *   npx tailwindcss -i tailwind.input.css -o shared-frontend/tailwind.css --minify
 */
module.exports = {
  content: ["./shared-frontend/**/*.{html,js}"],
  theme: { extend: {} },
  plugins: [],
};
